### ISSUE TITLE
how to use？

### ISSUE THREAD

**Issue by Liaoer** [yika-aixi/IcSkillSystem#3]

**Comment by yika-aixi** [comment]
demo:https://github.com/yika-aixi/SurvivalShooter-IcSkillSystem

**Comment by yika-aixi** [comment]
Project Browser Right `CabinIcarus/IcSkillSystem/Group` Create Skill Group

**Comment by Liaoer** [comment]
SurvivalShooter-IcSkillSystem can't run on unity 2019.3f1

**Comment by yika-aixi** [comment]
@Liaoer What error did you encounter? Send a screenshot, I've been busy recently,No time to look at the computer

**Comment by yika-aixi** [comment]
@Liaoer Use `0.7Sync` branch, fixed

**Comment by Liaoer** [comment]
git submodule update
error: no such remote ref 567ee2abb7629fa9a661582e59c80d9329b3cdad
Fetched in submodule path 'NPBehave', but it did not contain 567ee2abb7629fa9a661582e59c80d9329b3cdad. Direct fetching of that commit failed

**Comment by yika-aixi** [comment]
@Liaoer Modify the "NPBehave" remote git address to my fork

**Comment by Liaoer** [comment]
master branch?

**Comment by yika-aixi** [comment]
@Liaoer yes，You can also delete and re-clone. I have fixed this problem in previous commits.

**Comment by Liaoer** [comment]
SurvivalShooter-IcSkillSystem (0.7Sync)
IcSkillSystem (mater)
NPBehave (master)
xNode (master)
![image](https://user-images.githubusercontent.com/2783394/72629676-c2396480-398b-11ea-9ddf-f309c4f82f48.png)

**Comment by yika-aixi** [comment]
@Liaoer xNode is Cabin_Icarus branch

**Comment by Liaoer** [comment]
@yika-aixi checkout to Cabin_Icarus 
![image](https://user-images.githubusercontent.com/2783394/72631145-ce72f100-398e-11ea-8660-84196adf9f69.png)

**Comment by yika-aixi** [comment]
@Liaoer Please do not manually update submodules by yourself, the master branch, the commits used by submodules are relatively old, use git command "git submodule update --init"

**Comment by yika-aixi** [comment]
This is a simple getting started tutorial，https://b23.tv/av81968945/p1

**Comment by Liaoer** [comment]
@yika-aixi tks. it works.
