### ISSUE TITLE
PositionCreateGoNode异常问题

### ISSUE THREAD

**Issue by DangoRyn** [yika-aixi/IcSkillSystem#4]
PositionCreateGoNode脚本中，IcVariableBoolean _basedOnItselfPos = (IcVariableBoolean) true;报错InvalidCastException: Specified cast is not valid。导致序列化出错node节点出问题，改为IcVariableBoolean _basedOnItselfPos不赋值就没问题了。

还有就是有没有能够获取到挂载脚本的自身GameObject的方法，目前我做法是在Behave Start之前赋值一个self节点，后续很多时候会用到self节点的，或许是我用法不对，不知有没有更好的方案。

**Comment by yika-aixi** [comment]
PositionCreateGoNode 晚上我回去看看，至于获取go问题，每个节点都有IcSkillGroup成员，IcSkillGroup中有Owner成员

**Comment by yika-aixi** [comment]
@Dango1992 要在可视化访问可以加一个变量节点返回，我晚上加一个，你用的是什么分支master？

**Comment by DangoRyn** [comment]
> @ Dango1992要在可视化访问可以加一个变量变量返回，我晚上加一个，你用的是什么分开master？

我用的0.7得那个分支，unity版本 2018.3，没用2019版，PositionCreateGoNode异常不知和我unity版本有没有关系。

**Comment by yika-aixi** [comment]
@Dango1992 应该不是版本问题，我晚上看看

**Comment by yika-aixi** [comment]
@Dango1992 想了下没必要加一个变量节点输出go，直接group.owner就行，然后PositionCreateGoNode我看了下代码，不应该出现异常，你可以把代码发上来看看嘛
